<div id="content">
	<div class="gradientContent">
		<div class="feature-left">
			<h1 class="logo">Goodat</h1>		
		</div>
		
		<div class="feature-right">
			<div class="mainRegContainer">
					<h1>Register</h1>
					<h3 class="subHead">You're just 10 seconds away from start to share your skill</h3>
				
					<div class="reg-content">
						<?php echo $this->form; ?>
					</div>			
			</div>
		</div>
		
	</div>
</div>