<div id="logout-container">
	<div id="content">
		<div class="gradientContent">
		<a href="/login" class="login-button">Log in<b></b></a>
			<div class="feature-right">
				<div class="goodatImage">
				</div>
			</div>
			
			<div class="feature-left">
				<h1 class="logo">Goodat</h1>
				<h2 class="description">Share your skills<br> with anyone anywhere</h2>
				<div class="register-container">
					<a href="/register" class="register-button">share your skill</a>
				</div>
			</div>
		</div>	
	</div> 
</div>

<?php //echo $this->loggedUser() ?>