<?php $this->layout()->setLayout('users'); ?>

<div  class="intro-left">
	<h1>Start teaching your skills</h1>
	<h2>
		We each have skills and abilities that is good in them <br>so why do not we start to share them with others?<br>
		Anyone can teach and learn<br> Goodat lets you turn your skills to your business.
	</h2>
	<div>
		<a class="left-btn" href="<?php 
			echo $this->url(array('controller'=>'classes','action'=>'add'));?>">Open Class</a></p>
	</div>
</div>

<div class="intro-right">
	<div class="teachImage">
		<img src="/img/teachimage.jpg">
	</div>
</div>