<div id="content">
	<div class="gradientContent">
		<div class="feature-left">
			<h1 class="logo">Goodat</h1>		
		</div>
		
		<div class="feature-right">
			<div class="mainRegContainer">
					<h1>Login</h1>
					<h3>Not a member yet? <a href="/register">Register now</a> 
					— and start share your skill
					</h3>
					<div class="reg-content">
						<?php
    						if (isset($this->errorMessage)) {
        						echo '<b>' . $this->errorMessage . '</b>';
    						}
						?>
							<?php echo $this->form; ?>
					</div>			
			</div>
		</div>
		
	</div>
</div>
