<?php $this->layout()->setLayout('users'); ?>

<div id="page-header">
	<h1>Find Classes</h2>
</div>

<div class="left-column">
	<div class="class-detailes">
		<div class="class-inner">
			<?php foreach($this->classes as $class):?>
    						<div class="class-wrapper">
    							<div class="class-info">
    								<div class="class-header">
    									<div class="class-title">
    										<a href="<?php echo 
    													   $this->url(array('controller'=>'classes','action'=>'class','id'=>$class->id));?>">
    													   <h2><?php echo $this->escape($class->title);?></h2></a>
    									
    								</div>
    							</div>
    							
    						</div>		
		</div>
	<?php endforeach; ?>
	</div>
	
</div>



